FROM ubuntu:22.04

# Install Pico Compilation Requirements
RUN apt update && apt install -y gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential cmake ninja-build 

RUN apt install git python3 libusb-1.0-0-dev -y
